### PR TITLE
Multiple recognition support

### PR DESCRIPTION
**Pull request by chivincent**
For supporting multiple recognition engine, there're several changes in this PR:

- Added `Recognizer` into `Config.yml`
    - User can choose which Recognizer to use
- Added `RateLimiter` into `Config.yml`
    - Offline engines (Vosk API) can disable rate limiter
- Added Vosk API support
    - Upgrade SpeechRecognition to 3.9.0
    - Added guide into README.md
 
Because there is an [issue (#659)](https://github.com/Uberi/speech_recognition/issues/659) in SpeechRecognition package, I don't want to integrate OpenAI whisper in this PR (even it is better than Vosk API in my testing).

### CODE REVIEW

**Comment by cyberkitsune** [comment]
Hey there, I was currently already working on vosk support / multiple recognizers in the feat/vosk branch here: https://github.com/cyberkitsune/vrc-osc-scripts/tree/feat/vosk

I'll open a WIP PR for now to avoid any confusion 😅

**Comment by chivincent** [comment]
I got it, but it is not a PR for supporting vosk API only. I think it is a good idea to merge some commits into `feat/vosk` branch, isn't it?

- Changes for rate limiter maybe useful when using offline engine.
- Some recognition engines in SpeechRecognition package with different parameters, I think it can also managed by `Config.yml`
    - OpenAI Whisper engine: model type, translate and others
    - Azure API: api key for azure service

**Comment by cyberkitsune** [comment]
> * Changes for rate limiter maybe useful when using offline engine.

The rate limiter is to satisfy VRChat's chatbox update requirement, not so save on network bandwith. If users turn it off they'd likely hit the VRC chatbox timeout which locks out all new messages for 60 seconds (if you exceed 5 messages over 5 seconds, which could happen easily when using vosk w/o the limiter)

> * Some recognition engines in SpeechRecognition package with different parameters,

The PR I've been working on already sets up support for even more recognizers, though the use of python function pointers. If the arguments don't match you could point it to a wrapper function.

Eventually I want to abstract the entire recognizer system into abstract base classes as the main script is getting too cluttered as it is; That's the main reason I wanted to use a function pointer table, I wanted to avoid nested IFs and the like in the main script ^^

>  I think it can also managed by `Config.yml`

The current config file is getting a little cluttered too. I already get a lot of Discord support messages about it, I fear that adding too much will be confusing. For example, if an option for an Azure API key is sitting there, somebody could get confused and think they need one for Google as well.

Ultimately I think individual recognizers should have their own YML, and only the options to pick which recognizer should live in `Config.yml` -- This should help keep the main config file clean for the most part.

**Comment by chivincent** [comment]
Thanks for replying. 

It is a good idea for configurable rate limiter for VRC client. I can't wait for this feature implementing.

Otherwise, when I was trying to implement multiple recognizers feature, I thought about using function pointer, but after considering that each recognizer may have different parameters, I abandoned the idea of table of function pointer.

Finally, for this PR implementation for Config.yml, I originally considered the following format:

```yml
# ...
Recognizer:
  Engine: 'azure'

  # For Azure engine configuration
  Azure:
    key: 'this_is_key_of_azure_service'

  # For Google Cloud configuration
  # GoogleCloud:
  #   credentials_json: |
  #     { 'type': "service_account", 'project_id': "demo_for_vrc", "private_key_id": "...", ... }
# ...
```

However, parted configuration also sounds great.

**Comment by cyberkitsune** [comment]
I merged my existing vosk setup into main -- I also added rate limit customization!

Apologies for the confusion with concurrent work. Feel free to open another PR if you have additional contributions!

Closing this for now.

**Comment by chivincent** [comment]
It's ok. I'm glad to join this repository.

If need any help, feel free to contact me.

**Pull request closed without merging**
